AmazonPay as a Tradittional Payment Option - Product Page and Mini Cart Placements - Support Alexa Delivery notifications
woocommerce/woocommerce-gateway-amazon-pay pull request #174
Opened 2022-04-19 21:19 UTC by dpanta94

### All Submissions:

* [x] Does your code follow the [Extendables](https://extendomattic.wordpress.com/standardizations/) standards?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully run tests with your changes locally?

### Changes proposed in this Pull Request:
#### Introduce Amazon Pay as a traditional WooCommerce Gateway Option.
* Adds Amazon Pay as a tradditional gateway option. [SauCal pull#145](https://github.com/saucal/woocommerce-gateway-amazon-pay/pull/145)
* Adds Amazon Pay "classic" support for the WooCommerce Checkout Block. [SauCal pull#155](https://github.com/saucal/woocommerce-gateway-amazon-pay/pull/155)
* Makes a phone to be supplied required, when using Amazon Pay "classic". [SauCal pull#157](https://github.com/saucal/woocommerce-gateway-amazon-pay/pull/157)
* Fixes a possible overwrite. [SauCal pull#159](https://github.com/saucal/woocommerce-gateway-amazon-pay/pull/159)

Introduces Amazon Pay as a traditional WooCommerce Gateway based on an option in the plugin settings, which we will be referring to as 'classic'.

Key differences when using the classic option is we need to provide to Amazon the shipping details of the order if the order needs shipping and the customer doesn't have the chance to review the order after being redirected to Amazon since he is going to complete his checkout process there and then he will return to merchant's site.

In the order-pay endpoint, we had to change where the already implemented checkout button was appearing in order to put the classic method in its place. Its still available, but now appearing in the same place as in the checkout page.

Technical Details

We have implemented the integration named "Additional payment button" by Amazon.
@see https://developer.amazon.com/docs/amazon-pay-apb-checkout/additional-payment-button-overview.html

In the checkout endpoint, when Amazon classic is selected as the payment method. Gateway's process_payment method
returns a result object containing all the required params for the JS to create an Amazon button to initiate the payment, while also providing a redirect value to a HTML element of the same page that does not exists so that JS will have the chance to initiate the Amazon process. JS hooks on the 'checkout_place_order_success", creates the Amazon button hidden and then triggers a click on it for the process to be initiated. That way the flow appears to the end customer as a one-step process.

In the order-pay endpoint, when Amazon classic is selected as the payment method. We overwrite the form's default functionality to an AJAX request in our own endpoint in order to follow the same process as in the checkout endpoint.

Provides the functionality for integrating Amazon Pay "Classic" on the checkout block of WooCommerce blocks.

#### Adds support for Amazon Pay in WooCommerce's mini cart
* Adds support for Amazon Pay placement in the mini-cart. [SauCal pull#146](https://github.com/saucal/woocommerce-gateway-amazon-pay/pull/146)
* Fixes button's margins. [SauCal pull#161](https://github.com/saucal/woocommerce-gateway-amazon-pay/pull/161)
* Refreshes data on wc_fragments_refreshed too. [SauCal pull#163](https://github.com/saucal/woocommerce-gateway-amazon-pay/pull/163)

Adds support for the Amazon Pay button in the WooCommerce's mini cart.

#### Adds support for Amazon Pay in Product Pages
* Adds support for the Amazon Pay button in Product Pages.. [SauCal pull#147](https://github.com/saucal/woocommerce-gateway-amazon-pay/pull/147)
* CSS and output amends. [SauCal pull#160](https://github.com/saucal/woocommerce-gateway-amazon-pay/pull/160)

Adds support for the Amazon Pay button in Product Pages.

Technical details

When the amazon pay button located in the product page is clicked an AJAX request is taking place which saves the active cart
in WooCommerce's session, empties current cart and adds only the selected product and finally provides the JS with required parameters for amazon to initiate the new checkout session.

When the checkout session is completed, the cart that was stored gets restored.

#### Adds support for Alexa Delivery notifications
* Adds support for Alexa Delivery Notifications. [SauCal pull#148](https://github.com/saucal/woocommerce-gateway-amazon-pay/pull/148)

Adds support for Alexa Delivery Notifications. Shipping plugins can simply call

`do_action( 'apa_enable_alexa_notifications', $tracking_number, $carrier, $order_id );`

in a time where wc_get_order is applicable to be called, and as long as the merchant has enabled the corresponding option, alexa delivery notifications will be enabled for the $order_id.

#### Generic
##### Fixes Gateway's availability determination
* [SauCal pull#151](https://github.com/saucal/woocommerce-gateway-amazon-pay/pull/151)
* [SauCal pull#154](https://github.com/saucal/woocommerce-gateway-amazon-pay/pull/154)
##### Update package.json
* [SauCal pull#156](https://github.com/saucal/woocommerce-gateway-amazon-pay/pull/156)
##### Honor subscription support option for all placements
* [SauCal pull#158](https://github.com/saucal/woocommerce-gateway-amazon-pay/pull/158)
##### Fixes Naming convections / Typo / PHPCS
* [SauCal pull#162](https://github.com/saucal/woocommerce-gateway-amazon-pay/pull/162)
### Other information:
This is a PR consisting of 15 smaller PRs (all links provided).
Main purpose is to introduce 4 new features.
- Amazon Pay as a tradittional payment option support
- Amazon Pay in the mini-cart placement support
- Amazon Pay in the product page placement support
- Alexa delivery notifications support

* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changelog entry

> Add - Introduces Amazon Pay as a traditional WooCommerce Gateway.
> Add - 3 new options. For controlling the traditional appearance of Amazon Pay, gateway's title and description.
> Add - Supports Amazon Pay "Classic" on the checkout block of WooCommerce Blocks.
> Add - Support for Amazon Pay in WooCommerce's mini cart.
> Add - Support for Amazon Pay button on Product pages.
> Add - Support for Alexa Delivery Notifications

2022-04-20 13:14 UTC, kalessil requested changes
Did the first review round and I like the overall direction here.

I left my comments and the most of them are around:
- not using shortenings like `btn`, `amzn`, `elem`
- naming conventions consistency (in PHP we use Snake case and in React components Camel case)

Consistency is also important, so in some parts of JS where Snake case is already used, we can keep using it.

2022-04-20 13:14 UTC, kalessil commented on src/renderAmazonButton.js
> +		const button_settings = getButtonSettings(
We have inconsistent naming conventions here.

2022-04-20 13:14 UTC, kalessil commented on src/utils.js
> +export const getSiblings = ( elem, className ) => {
Also shortenings.

2022-04-20 13:14 UTC, kalessil commented on src/utils.js
> +	const amzPayServerData = wc.wcSettings.getSetting( name, null );
Also shortenings.

2022-04-20 13:14 UTC, kalessil commented on assets/js/amazon-wc-checkout.js
> +			var dataCont = 'cart' === flag ? $( '#wc-apa-update-vals-cart' ) : $( '#wc-apa-update-vals' );
Also shortening?

2022-04-20 13:14 UTC, kalessil commented on assets/js/amazon-wc-checkout.js
> +				var button_settings = getButtonSettings( buttonSettingsFlag );
We have inconsistent naming conventions here.

2022-04-20 13:14 UTC, kalessil commented on assets/js/amazon-wc-checkout.js
> +		var amzCreateCheckoutConfig = null;
Also, we have inconsistent naming style here.

2022-04-21 13:44 UTC, dpanta94 commented
Hey @kalessil ! We have made amends for all your comments above. Thank you!

2022-04-22 07:55 UTC, kalessil approved these changes
LGTM!

2022-04-22 07:56 UTC, merged